In [69]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import train_test_split

In [70]:
np.random.seed(0)
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [71]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [72]:
df['Flower_species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

    Flower_species  
0           setosa  
1           setosa  
2           setosa  
3           setosa  
4           setosa  
..             ...  
145      virginica  
146      virginica  
147      virginica  
148      virginica  
149      virginica  

[150 rows x 5 columns]

In [73]:
df['train'] = np.random.uniform(0,1,len(df))<=0.70
df['train'].value_counts()

True     111
False     39
Name: train, dtype: int64

In [74]:
X,Y = df[df['train'] == True] , df[df['train'] == False]
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
..                 ...               ...                ...               ...   
138                6.0               3.0                4.8               1.8   
139                6.9               3.1                5.4               2.1   
141                6.9               3.1                5.1               2.3   
142                5.8               2.7                5.1               1.9   
146                6.3               2.5                5.0               1.9   

    Flower_species  train  
0           setosa   True  
2           setosa   True  
3           setosa   True  
4           setosa   True  
5           setosa   True  
..             ...    ...  
138      virginica   True  
139      virginica   True  
141      virginica   True  
142      virginica   True  
146      virginica   True  

[111 rows x 6 columns]

In [75]:
Y

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
1                  4.9               3.0                1.4               0.2   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
10                 5.4               3.7                1.5               0.2   
13                 4.3               3.0                1.1               0.1   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
23                 5.1               3.3                1.7               0.5   
27                 5.2               3.5                1.5               0.2   
31                 5.4               3.4                1.5               0.4   
38                 4.4               3.0                1.3               0.2   
52                 6.9               3.1                4.9               1.5   
66                 5.6               3.0                4.5               1.5   
68                 6.2               2.2                4.5               1.5   
70                 5.9               3.2                4.8               1.8   
72                 6.3               2.5                4.9               1.5   
74                 6.4               2.9                4.3               1.3   
89                 5.5               2.5                4.0               1.3   
93                 5.0               2.3                3.3               1.0   
98                 5.1               2.5                3.0               1.1   
102                7.1               3.0                5.9               2.1   
103                6.3               2.9                5.6               1.8   
109                7.2               3.6                6.1               2.5   
111                6.4               2.7                5.3               1.9   
114                5.8               2.8                5.1               2.4   
116                6.5               3.0                5.5               1.8   
118                7.7               2.6                6.9               2.3   
120                6.9               3.2                5.7               2.3   
122                7.7               2.8                6.7               2.0   
140                6.7               3.1                5.6               2.4   
143                6.8               3.2                5.9               2.3   
144                6.7               3.3                5.7               2.5   
145                6.7               3.0                5.2               2.3   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

    Flower_species  train  
1           setosa  False  
7           setosa  False  
8           setosa  False  
10          setosa  False  
13          setosa  False  
17          setosa  False  
18          setosa  False  
19          setosa  False  
20          setosa  False  
21          setosa  False  
23          setosa  False  
27          setosa  False  
31          setosa  False  
38          setosa  False  
52      versicolor  False  
66      versicolor  False  
68      versicolor  False  
70      versicolor  False  
72      versicolor  False  
74      versicolor  False  
89      versicolor  False  
93      versicolor  False  
98      versicolor  False  
102      virginica  False  
103      virginica  False  
109      virginica  False  
111     

In [76]:
feat = df.columns[:4]
feat

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [77]:
x = pd.factorize(X['Flower_species'])[0]
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2], dtype=int64)

In [78]:
rfc = RandomForestClassifier(n_jobs = 2, random_state = 0)
rfc.fit(X[feat],x)

RandomForestClassifier(n_jobs=2, random_state=0)

In [79]:
y_pred = rfc.predict(Y[feat])
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [80]:
y = pd.factorize(Y['Flower_species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [81]:
predn = iris.target_names[y_pred]

In [82]:
predn[0:10]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [85]:
pd.crosstab(Y['Flower_species'],predn,rownames = ['Actual'],colnames = ['Predicted'])

Predicted   setosa  versicolor  virginica
Actual                                   
setosa          14           0          0
versicolor       0           7          2
virginica        0           0         16

In [86]:
accuracy = 100*(14+7+16)/(14+7+2+16)
print(accuracy)

94.87179487179488
